/// Flutter icons CobanIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CobanIcons
///      fonts:
///       - asset: fonts/CobanIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class CobanIcons {
  CobanIcons._();

  static const _kFontFam = 'CobanIcons';
  static const String? _kFontPkg = null;

  static const IconData youtube_105 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chatboticon =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeicon =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
