name: cobanacademy
description: "Coban Academy APP"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  qr_flutter: ^4.1.0
  animate_do: ^3.3.4
  flutter_native_splash: ^2.3.13
  flutter_launcher_icons: ^0.13.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_chat_ui: ^1.6.12
  fluttericon: ^2.0.0
  dynamic_tabbar: ^1.0.6
  graphql_flutter: ^5.1.0
  flutter_svg: ^2.0.9
  page_transition: ^2.1.0
  page_view_dot_indicator: ^2.3.0
  responsive_sizer: ^3.3.0+1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  provider: ^6.1.2
  share_plus: ^7.2.2
  persistent_bottom_nav_bar: ^5.0.2
  video_player: ^2.8.6
  pod_player: ^0.2.2
  http: ^1.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  fonts:
    - family: CobanIcons
      fonts:
        - asset: assets/fonts/CobanIcons.ttf
    - family: MonaSans
      fonts:
        - asset: assets/fonts/MonaSans-Regular.ttf
        - asset: assets/fonts/MonaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/MonaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/MonaSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/MonaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MonaSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/MonaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/MonaSans-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/MonaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/MonaSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/MonaSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/MonaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MonaSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_native_splash:
  color: "6c5ad4"
  android_12:
    image: assets/images/bg.png
    color: "6c5ad4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app.png"
    background_color: "#6c5ad4"
    theme_color: "#6c5ad4"
  windows:
    generate: true
    image_path: "assets/images/app.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app.png"